# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/adventures_with_ip.xdc

# Block Designs: bd/ip_design/ip_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ip_design || ORIG_REF_NAME==ip_design}]

# IP: bd/ip_design/ip/ip_design_led_controller_0_0/ip_design_led_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ip_design_led_controller_0_0 || ORIG_REF_NAME==ip_design_led_controller_0_0}]

# IP: bd/ip_design/ip/ip_design_processing_system7_0_0/ip_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ip_design_processing_system7_0_0 || ORIG_REF_NAME==ip_design_processing_system7_0_0}]

# IP: bd/ip_design/ip/ip_design_processing_system7_0_axi_periph_0/ip_design_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ip_design_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==ip_design_processing_system7_0_axi_periph_0}]

# IP: bd/ip_design/ip/ip_design_rst_processing_system7_0_100M_0/ip_design_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ip_design_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==ip_design_rst_processing_system7_0_100M_0}]

# IP: bd/ip_design/ip/ip_design_xbar_0/ip_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ip_design_xbar_0 || ORIG_REF_NAME==ip_design_xbar_0}]

# IP: bd/ip_design/ip/ip_design_zed_audio_ctrl_0_0/ip_design_zed_audio_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ip_design_zed_audio_ctrl_0_0 || ORIG_REF_NAME==ip_design_zed_audio_ctrl_0_0}]

# IP: bd/ip_design/ip/ip_design_axi_gpio_0_0/ip_design_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ip_design_axi_gpio_0_0 || ORIG_REF_NAME==ip_design_axi_gpio_0_0}]

# IP: bd/ip_design/ip/ip_design_axi_gpio_1_0/ip_design_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ip_design_axi_gpio_1_0 || ORIG_REF_NAME==ip_design_axi_gpio_1_0}]

# IP: bd/ip_design/ip/ip_design_distortion_ip_0_0/ip_design_distortion_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ip_design_distortion_ip_0_0 || ORIG_REF_NAME==ip_design_distortion_ip_0_0}]

# IP: bd/ip_design/ip/ip_design_auto_pc_0/ip_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ip_design_auto_pc_0 || ORIG_REF_NAME==ip_design_auto_pc_0}]

# XDC: bd/ip_design/ip/ip_design_processing_system7_0_0/ip_design_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ip_design_processing_system7_0_0 || ORIG_REF_NAME==ip_design_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/ip_design/ip/ip_design_rst_processing_system7_0_100M_0/ip_design_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ip_design_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==ip_design_rst_processing_system7_0_100M_0}]

# XDC: bd/ip_design/ip/ip_design_rst_processing_system7_0_100M_0/ip_design_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ip_design_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==ip_design_rst_processing_system7_0_100M_0}]

# XDC: bd/ip_design/ip/ip_design_rst_processing_system7_0_100M_0/ip_design_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/ip_design/ip/ip_design_xbar_0/ip_design_xbar_0_ooc.xdc

# XDC: bd/ip_design/ip/ip_design_axi_gpio_0_0/ip_design_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ip_design_axi_gpio_0_0 || ORIG_REF_NAME==ip_design_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/ip_design/ip/ip_design_axi_gpio_0_0/ip_design_axi_gpio_0_0_ooc.xdc

# XDC: bd/ip_design/ip/ip_design_axi_gpio_0_0/ip_design_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ip_design_axi_gpio_0_0 || ORIG_REF_NAME==ip_design_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/ip_design/ip/ip_design_axi_gpio_1_0/ip_design_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ip_design_axi_gpio_1_0 || ORIG_REF_NAME==ip_design_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/ip_design/ip/ip_design_axi_gpio_1_0/ip_design_axi_gpio_1_0_ooc.xdc

# XDC: bd/ip_design/ip/ip_design_axi_gpio_1_0/ip_design_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ip_design_axi_gpio_1_0 || ORIG_REF_NAME==ip_design_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/ip_design/ip/ip_design_auto_pc_0/ip_design_auto_pc_0_ooc.xdc

# XDC: bd/ip_design/ip_design_ooc.xdc
