# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Zynk_test/lowlag_test/lowlag_test.cache/wt [current_project]
set_property parent.project_path C:/Zynk_test/lowlag_test/lowlag_test.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths c:/Zynk_Book/ip_repo [current_project]
add_files C:/Zynk_test/lowlag_test/lowlag_test.srcs/sources_1/bd/ip_design/ip_design.bd
set_property used_in_implementation false [get_files -all C:/Zynk_test/lowlag_test/lowlag_test.srcs/sources_1/bd/ip_design/ip/ip_design_processing_system7_0_0/ip_design_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all C:/Zynk_test/lowlag_test/lowlag_test.srcs/sources_1/bd/ip_design/ip/ip_design_rst_processing_system7_0_100M_0/ip_design_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all C:/Zynk_test/lowlag_test/lowlag_test.srcs/sources_1/bd/ip_design/ip/ip_design_rst_processing_system7_0_100M_0/ip_design_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all C:/Zynk_test/lowlag_test/lowlag_test.srcs/sources_1/bd/ip_design/ip/ip_design_rst_processing_system7_0_100M_0/ip_design_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Zynk_test/lowlag_test/lowlag_test.srcs/sources_1/bd/ip_design/ip/ip_design_xbar_0/ip_design_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Zynk_test/lowlag_test/lowlag_test.srcs/sources_1/bd/ip_design/ip/ip_design_axi_gpio_0_0/ip_design_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all C:/Zynk_test/lowlag_test/lowlag_test.srcs/sources_1/bd/ip_design/ip/ip_design_axi_gpio_0_0/ip_design_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Zynk_test/lowlag_test/lowlag_test.srcs/sources_1/bd/ip_design/ip/ip_design_axi_gpio_0_0/ip_design_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all C:/Zynk_test/lowlag_test/lowlag_test.srcs/sources_1/bd/ip_design/ip/ip_design_axi_gpio_1_0/ip_design_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all C:/Zynk_test/lowlag_test/lowlag_test.srcs/sources_1/bd/ip_design/ip/ip_design_axi_gpio_1_0/ip_design_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Zynk_test/lowlag_test/lowlag_test.srcs/sources_1/bd/ip_design/ip/ip_design_axi_gpio_1_0/ip_design_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Zynk_test/lowlag_test/lowlag_test.srcs/sources_1/bd/ip_design/ip/ip_design_auto_pc_0/ip_design_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Zynk_test/lowlag_test/lowlag_test.srcs/sources_1/bd/ip_design/ip_design_ooc.xdc]
set_property is_locked true [get_files C:/Zynk_test/lowlag_test/lowlag_test.srcs/sources_1/bd/ip_design/ip_design.bd]

read_vhdl -library xil_defaultlib C:/Zynk_test/lowlag_test/lowlag_test.srcs/sources_1/bd/ip_design/hdl/ip_design_wrapper.vhd
read_xdc C:/Zynk_test/lowlag_test/lowlag_test.srcs/constrs_1/imports/constraints/adventures_with_ip.xdc
set_property used_in_implementation false [get_files C:/Zynk_test/lowlag_test/lowlag_test.srcs/constrs_1/imports/constraints/adventures_with_ip.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top ip_design_wrapper -part xc7z020clg484-1
write_checkpoint -noxdef ip_design_wrapper.dcp
catch { report_utilization -file ip_design_wrapper_utilization_synth.rpt -pb ip_design_wrapper_utilization_synth.pb }
